### ISSUE TITLE
crash if slide progress bar in case of empty playlist.

### ISSUE THREAD

**Issue by iRajul** [jeancsanchez/JcPlayer#29]
`com.example.jean.jcplayer.JcPlayerService.seekTo(JcPlayerService.java:192)
                                                                       at com.example.jean.jcplayer.JcAudioPlayer.seekTo(JcAudioPlayer.java:166)
                                                                       at com.example.jean.jcplayer.JcPlayerView.onProgressChanged(JcPlayerView.java:403)
                                                                       at android.widget.SeekBar.onProgressRefresh(SeekBar.java:91)
                                                                       at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:660)
                                                                       at android.widget.ProgressBar.refreshProgress(ProgressBar.java:672)
                                                                       at android.widget.ProgressBar.setProgress(ProgressBar.java:719)
                                                                       at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:451)
                                                                       at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:372)
                                                                       at android.view.View.dispatchTouchEvent(View.java:7713)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2329)
                                                                       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1568)`

**Comment by jakirseu** [comment]
Same issue, if you fix it, kindly give us an update.

**Comment by iRajul** [comment]
@jakirseu I forked and solved there. 
https://github.com/iRajul/JcPlayer

**Comment by jeancsanchez** [comment]
@iRajul Send me a PR?

**Comment by iRajul** [comment]
@jeancsanchez  crated a PR at https://github.com/jeancsanchez/JcPlayer/pull/30
