### ISSUE TITLE
Error when click Previous button

### ISSUE THREAD

**Issue by dwjustine** [jeancsanchez/JcPlayer#42]
I try to click previous button before play and then i got a force close

java.lang.NullPointerException: Attempt to invoke virtual method 'long com.example.jean.jcplayer.JcAudio.getId()' on a null object reference
                                                                                at com.example.jean.jcplayer.JcAudioPlayer.updatePositionAudioList(JcAudioPlayer.java:197)
                                                                                at com.example.jean.jcplayer.JcAudioPlayer.previousAudio(JcAudioPlayer.java:154)
                                                                                at com.example.jean.jcplayer.JcPlayerView.previous(JcPlayerView.java:403)
                                                                                at com.example.jean.jcplayer.JcPlayerView.onClick(JcPlayerView.java:436)
                                                                                at android.view.View.performClick(View.java:5610)
                                                                                at android.view.View$PerformClick.run(View.java:22277)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:159)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6097)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by peace-shillong** [comment]
I've done a minor edit to the JCPlayerView class and submitted a pull request #45  yesterday hope it helps. 
Now the Player doesn't closes/crash - you can make a Toast and tell the user that there are no songs to play by the player.
