### ISSUE TITLE
unable to start activity - Error inflating class com.example.jean.jcplayer.JcPlayerView

### ISSUE THREAD

**Issue by abhatnagar03** [jeancsanchez/JCPlayer#61]
**Below is how I have integrated the library** 

**Project Gradle:**
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        maven {
            url "http://dl.bintray.com/jeancsanchez/maven"
        }
        google()
        jcenter()
    }
}

**App gradle:**
implementation 'com.github.jeancsanchez:JcPlayer:2.6.11'

**Gradle build is successful but I am getting below exception on starting the activity.**

**Logs:**

Process: com...., PID: 9380
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.activity.MainActivity}: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class com.example.jean.jcplayer.JcPlayerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3197)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7428)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class com.example.jean.jcplayer.JcPlayerView
     Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class com.example.jean.jcplayer.JcPlayerView
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.jean.jcplayer.JcPlayerView" on path: DexPathList[[zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/base.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_resources_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.ysa.pravachan.activity.MainActivity.onCreate(MainActivity.java:65)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
07-23 10:05:16.086 9380-9380/com.ysa.pravachan E/AndroidRuntime:     at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7428)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.ysa.pravachan-XRbnHK8rXWUJHn49yiAEfA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:716)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:749)
        at android.app.LoadedApk.getResources(LoadedApk.java:996)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2489)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6401)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1966)

**Comment by abhatnagar03** [comment]
@jeancsanchez It's because the package is changed to com.example.jean.jcplayer.view.JcPlayerView.

I would recommend to update the readme.

Thanks
