### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by rohankandwal** [jeancsanchez/JCPlayer#82]
Got this on Fabric for a couple of devices.
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.example.jean.jcplayer.JcPlayerManager.onTimeChangedListener(JcPlayerManager.kt:265)
       at com.example.jean.jcplayer.service.JcPlayerService$updateTime$1.run(JcPlayerService.kt:280)
```

**Comment by jeancsanchez** [comment]
@rohankandwal  Fixed on the last version 2.6.15
