### ISSUE TITLE
ArrayIndexOutOfBoundsException on CreateNotificationPlayer

### ISSUE THREAD

**Issue by choirunnisa** [jeancsanchez/JCPlayer#84]
First of all, thank you for creating this plugin! 👍  

Found this error on my Firebase Crashlytics happening for many of my users.

JcNotificationPlayer line 95

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
length=4; index=5
com.example.jean.jcplayer.service.notification.JcNotificationPlayer.createNotificationPlayer (SourceFile:95)

Do you have any idea what went wrong?

**Comment by jeancsanchez** [comment]
@choirunnisa Thanks!
Is it the same error as  #23 ? If so, I didn't get a solution for this :(

**Comment by josef130** [comment]
i have the same problem :

`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
       at android.util.ArraySet.add + 387(ArraySet.java:387)
       at android.app.Notification.-android_app_Notification_lambda$1 + 1864(Notification.java:1864)
       at android.app.Notification$-void_writeToParcel_android_os_Parcel_parcel_int_flags_LambdaImpl0.onMarshaled(Notification.java)
       at android.app.PendingIntent.writeToParcel + 1051(PendingIntent.java:1051)
       at android.widget.RemoteViews$SetOnClickPendingIntent.writeToParcel + 762(RemoteViews.java:762)
       at android.widget.RemoteViews.writeToParcel + 3498(RemoteViews.java:3498)
       at android.app.Notification.writeToParcelImpl + 1923(Notification.java:1923)
       at android.app.Notification.writeToParcel + 1871(Notification.java:1871)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag + 835(INotificationManager.java:835)
       at android.app.NotificationManager.notifyAsUser + 313(NotificationManager.java:313)
       at android.app.NotificationManager.notify + 284(NotificationManager.java:284)
       at android.support.v4.app.ba.a()
       at android.support.v4.app.ba.a()
       at com.example.jean.jcplayer.service.notification.a.a()
       at com.example.jean.jcplayer.service.notification.a.c()
       at b.b.a.a.a.b()
       at com.example.jean.jcplayer.service.b.run()`
