### ISSUE TITLE
am getting jcPlayerService  Null object error

### ISSUE THREAD

**Issue by prakashmp** [jeancsanchez/JCPlayer#87]
FATAL EXCEPTION: main
                                                                    Process: com.emenator.android, PID: 2767
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.jean.jcplayer.JcPlayerService.registerNotificationListener(com.example.jean.jcplayer.JcPlayerView$JcPlayerViewServiceListener)' on a null object reference
                                                                        at com.example.jean.jcplayer.JcAudioPlayer.registerNotificationListener(JcAudioPlayer.java:63)
                                                                        at com.example.jean.jcplayer.JcNotificationPlayerService.createNotificationPlayer(JcNotificationPlayerService.java:48)
                                                                        at com.example.jean.jcplayer.JcNotificationPlayerService.onPlaying(JcNotificationPlayerService.java:130)
                                                                        at com.example.jean.jcplayer.JcPlayerService.play(JcPlayerService.java:233)
                                                                        at com.example.jean.jcplayer.JcPlayerService.play(JcPlayerService.java:190)
                                                                        at com.example.jean.jcplayer.JcAudioPlayer.playAudio(JcAudioPlayer.java:106)
                                                                        at com.example.jean.jcplayer.JcAudioPlayer$1.connected(JcAudioPlayer.java:96)
                                                                        at com.example.jean.jcplayer.JcAudioPlayer$2.onServiceConnected(JcAudioPlayer.java:242)
                                                                        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1660)
                                                                        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1689)
                                                                        at android.os.Handler.handleCallback(Handler.java:794)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        at android.os.Looper.loop(Looper.java:176)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6651)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
03-29 16:46:35.797 2767-2767/com.emenator.android E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.jean.jcplayer.JcPlayerService.registerNotificationListener(com.example.jean.jcplayer.JcPlayerView$JcPlayerViewServiceListener)' on a null object reference
                                                                           at com.example.jean.jcplayer.JcAudioPlayer.registerNotificationListener(JcAudioPlayer.java:63)
                                                                           at com.example.jean.jcplayer.JcNotificationPlayerService.createNotificationPlayer(JcNotificationPlayerService.java:48)
                                                                           at com.example.jean.jcplayer.JcNotificationPlayerService.onPlaying(JcNotificationPlayerService.java:130)
                                                                           at com.example.jean.jcplayer.JcPlayerService.play(JcPlayerService.java:233)
                                                                           at com.example.jean.jcplayer.JcPlayerService.play(JcPlayerService.java:190)
                                                                           at com.example.jean.jcplayer.JcAudioPlayer.playAudio(JcAudioPlayer.java:106)
                                                                           at com.example.jean.jcplayer.JcAudioPlayer$1.connected(JcAudioPlayer.java:96)
                                                                           at com.example.jean.jcplayer.JcAudioPlayer$2.onServiceConnected(JcAudioPlayer.java:242)
                                                                           at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1660)
                                                                           at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1689)
                                                                           at android.os.Handler.handleCallback(Handler.java:794)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:176)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6651)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by prakashmp** [comment]
Solution: I missed the unbind function.
